import { CommitDataObject } from "../../../../src/modules/TDDCycles/Domain/CommitDataObject";

export const githubResponseData = {
    headers: {},
    status: 200,
    url: 'https://api.github.com/repos/owner/repoName/commits',
    data: [
        {
            sha: 'commit1',
            node_id: 'node1',
            url: 'url1',
            html_url: 'html_url1',
            comments_url: 'comments_url1',
            author: {
                login: 'author1',
                id: 1,
                node_id: 'author_node1',
                avatar_url: 'avatar_url1',
                gravatar_id: 'gravatar_id1',
                url: 'author_url1',
                html_url: 'author_html_url1',
                followers_url: 'followers_url1',
                following_url: 'following_url1',
                gists_url: 'gists_url1',
                starred_url: 'starred_url1',
                subscriptions_url: 'subscriptions_url1',
                organizations_url: 'organizations_url1',
                repos_url: 'repos_url1',
                events_url: 'events_url1',
                received_events_url: 'received_events_url1',
                type: 'author_type1',
                site_admin: false,
            },
            committer: {
                login: 'committer1',
                id: 2,
                node_id: 'committer_node1',
                avatar_url: 'avatar_url2',
                gravatar_id: 'gravatar_id2',
                url: 'committer_url1',
                html_url: 'committer_html_url1',
                followers_url: 'committer_followers_url1',
                following_url: 'committer_following_url1',
                gists_url: 'committer_gists_url1',
                starred_url: 'committer_starred_url1',
                subscriptions_url: 'committer_subscriptions_url1',
                organizations_url: 'committer_organizations_url1',
                repos_url: 'committer_repos_url1',
                events_url: 'committer_events_url1',
                received_events_url: 'committer_received_events_url1',
                type: 'committer_type1',
                site_admin: false,
            },
            parents: [
                {
                    sha: 'parent1',
                    url: 'parent_url1',
                    html_url: 'parent_html_url1',
                },
            ],
            commit: {
                author: {
                    name: 'commit_author1',
                    email: 'commit_author_email1',
                    date: new Date(),
                },
                committer: {
                    name: 'commit_committer1',
                    email: 'commit_committer_email1',
                    date: new Date(),
                },
                message: 'commit_message1',
                tree: {
                    sha: 'tree1',
                    url: 'tree_url1',
                },
                url: 'commit_url1',
                comment_count: 1,
                verification: {
                    verified: true,
                    reason: 'verification_reason1',
                    signature: null,
                    payload: null,
                },
            },
        },
        // Add more mock commits here if needed
    ],
};

export const githubCommitData : CommitDataObject[] = [
    {
        sha: 'commit1',
        node_id: 'node1',
        url: 'url1',
        html_url: 'html_url1',
        comments_url: 'comments_url1',
        author: {
            login: 'author1',
            id: 1,
            node_id: 'author_node1',
            avatar_url: 'avatar_url1',
            gravatar_id: 'gravatar_id1',
            url: 'author_url1',
            html_url: 'author_html_url1',
            followers_url: 'followers_url1',
            following_url: 'following_url1',
            gists_url: 'gists_url1',
            starred_url: 'starred_url1',
            subscriptions_url: 'subscriptions_url1',
            organizations_url: 'organizations_url1',
            repos_url: 'repos_url1',
            events_url: 'events_url1',
            received_events_url: 'received_events_url1',
            type: 'author_type1',
            site_admin: false,
        },
        committer: {
            login: 'committer1',
            id: 2,
            node_id: 'committer_node1',
            avatar_url: 'avatar_url2',
            gravatar_id: 'gravatar_id2',
            url: 'committer_url1',
            html_url: 'committer_html_url1',
            followers_url: 'committer_followers_url1',
            following_url: 'committer_following_url1',
            gists_url: 'committer_gists_url1',
            starred_url: 'committer_starred_url1',
            subscriptions_url: 'committer_subscriptions_url1',
            organizations_url: 'committer_organizations_url1',
            repos_url: 'committer_repos_url1',
            events_url: 'committer_events_url1',
            received_events_url: 'committer_received_events_url1',
            type: 'committer_type1',
            site_admin: false,
        },
        parents: [
            {
                sha: 'parent1',
                url: 'parent_url1',
                html_url: 'parent_html_url1',
            },
        ],
        commit: {
            author: {
                name: 'commit_author1',
                email: 'commit_author_email1',
                date: expect.any(Date),
            },
            committer: {
                name: 'commit_committer1',
                email: 'commit_committer_email1',
                date: expect.any(Date),
            },
            message: 'commit_message1',
            tree: {
                sha: 'tree1',
                url: 'tree_url1',
            },
            url: 'commit_url1',
            comment_count: 1,
            verification: {
                verified: true,
                reason: 'verification_reason1',
                signature: null,
                payload: null,
            },
        },
    },
    // Add assertions for more mock commits here if needed
];