export const submissionTableStyles = {
  table: {
    borderCollapse: "collapse",
    tableLayout: "fixed",
  },
  headerRow: {
    borderBottom: "1px solid #C9C9C9",
  },
  headerCorreoCell: {
    fontWeight: 700,
    fontSize: "1.65rem",
    py: 1.3,
    width: "18%",
  },
  headerEstadoCell: {
    fontWeight: 700,
    fontSize: "1.65rem",
    py: 1.3,
    width: "11%",
    borderLeft: "1px solid #C9C9C9",
  },
  headerEnlaceCell: {
    fontWeight: 700,
    fontSize: "1.65rem",
    py: 1.3,
    width: "10%",
    borderLeft: "1px solid #C9C9C9",
  },
  headerFechaInicioCell: {
    fontWeight: 700,
    fontSize: "1.65rem",
    py: 1.3,
    width: "13%",
    borderLeft: "1px solid #C9C9C9",
  },
  headerFechaFinCell: {
    fontWeight: 700,
    fontSize: "1.65rem",
    py: 1.3,
    width: "14%",
    borderLeft: "1px solid #C9C9C9",
  },
  headerGraficaCell: {
    fontWeight: 700,
    fontSize: "1.65rem",
    py: 1.3,
    width: "13%",
    borderLeft: "1px solid #C9C9C9",
  },
  headerAsistenteCell: {
    fontWeight: 700,
    fontSize: "1.65rem",
    py: 1.3,
    width: "12%",
    borderLeft: "1px solid #C9C9C9",
  },
  headerAdicionalesCell: {
    fontWeight: 700,
    fontSize: "1.65rem",
    py: 1.3,
    width: "12%",
    borderLeft: "1px solid #C9C9C9",
  },
  row: {
    borderBottom: "1px solid #C9C9C9",
  },
  emailCell: {
    py: 2.2,
    fontSize: "1.3rem",
    maxWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusCell: (statusColor: string) => ({
    py: 2.2,
    fontSize: "1.3rem",
    color: statusColor,
    borderLeft: "1px solid #C9C9C9",
    whiteSpace: "nowrap",
  }),
  linkCell: {
    py: 2.2,
    borderLeft: "1px solid #C9C9C9",
    textAlign: "center",
  },
  linkIcon: {
    display: "inline-flex",
    alignItems: "center",
    color: "#5C6BC0",
  },
  dateCell: {
    py: 2.2,
    fontSize: "1.3rem",
    borderLeft: "1px solid #C9C9C9",
  },
  actionCell: {
    py: 2.2,
    borderLeft: "1px solid #C9C9C9",
  },
  actionButton: (disabled: boolean) => ({
    textTransform: "none",
    fontSize: "1.15rem",
    marginRight: "8px",
    backgroundColor: disabled ? "#BDBDBD" : undefined,
    minWidth: "110px",
  }),
  additionalActionButton: (disabled: boolean) => ({
    textTransform: "none",
    fontSize: "1.15rem",
    marginRight: "7px",
    backgroundColor: disabled ? "#BDBDBD" : undefined,
    minWidth: "84px",
  }),
};
